// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	feed "github.com/easycode666/douyin/cmd/api/biz/router/feed"
	user "github.com/easycode666/douyin/cmd/api/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	feed.Register(r)

	user.Register(r)
}
